connection to mqtt broker and subscribing to events
surjak/SmartParking pull request #1
Opened 2020-12-30 13:44 UTC by surjak

2020-12-30 21:09 UTC, HubertBalcerzak requested changes

2020-12-30 21:09 UTC, HubertBalcerzak commented on src/main/kotlin/pl/edu/agh/smartparking/mqtt/MqttCupCarbonMessage.kt
> +            }
```suggestion
fun fromStr(str: String): ParkingPlaceEvent = when (str) {
                TAKE_PLACE.name -> TAKE_PLACE
                LEAVE_PLACE.name -> LEAVE_PLACE
                else -> throw IllegalArgumentException()
            }
```

2020-12-30 21:09 UTC, HubertBalcerzak commented on src/main/kotlin/pl/edu/agh/smartparking/mqtt/MqttCupCarbonMessage.kt
> +
```suggestion
```

2020-12-30 21:09 UTC, HubertBalcerzak commented on src/main/kotlin/pl/edu/agh/smartparking/mqtt/MqttCupCarbonMessage.kt
> +            val carId = toInt(message)
```suggestion
            val floor = list[2].toInt()
            val parkingPlace = list[3].toInt()
            val carId = message.toInt()
```

2020-12-30 21:09 UTC, HubertBalcerzak commented on src/main/kotlin/pl/edu/agh/smartparking/mqtt/MqttCupCarbonMessage.kt
> +        }
```suggestion
```

2020-12-31 09:01 UTC, surjak commented
Poprawione 😃

2020-12-31 09:01 UTC, merged